default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: api

test:
  <<: *default
  database: api_demo

production:
  <<: *default
  database: api